### ISSUE TITLE
Release of pyQuEST package

### ISSUE THREAD

**Issue by TerraVenil** [rrmeister/pyQuEST#1]
Hi, I am just curious if you have any plans/estimations in the nearest future release of pyQuEST package?
I am looking for a Python interface to interact with the QuEST toolkit. So any kind of details regarding current progress and long term plans will be very helpful to make a correct decision on how to do such integration in the most efficient way.
Thanks.

**Comment by rrmeister** [comment]
Hi Oleksii!
Thanks very much for your interest in pyQuEST. I am currently implementing unit tests to make sure the interface operates as intended and has no incorrect edge cases. After that, we are pretty much ready for the first official release.
In any case, the package is ready to use as-is, just be a little more cautious than usual about verifying the results you obtain using pyQuEST.
Cheers!
Richard
