### ISSUE TITLE
No module named 'pyquest.core'

### ISSUE THREAD

**Issue by TerraVenil** [rrmeister/pyQuEST#2]
Hi, @rrmeister. I followed instructions from the develop branch and successfully built and installed pyquest but when I was trying to run it was missing some dependency. Can you help me to solve this issue?
```
>>> import pyquest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "***\pyQuEST\pyquest\__init__.py", line 7, in <module>
    from pyquest.core import QuESTEnvironment, Register, Circuit  # noqa: F401
ModuleNotFoundError: No module named 'pyquest.core'
```

**Comment by rrmeister** [comment]
Hi Oleksii!
I think you might have missed this important line in the readme:

> Make sure to not launch your interpreter from within the pyQuEST folder, as the pyquest source directory would take precedence over the installed package and cause the import to fail.

Can you start your interpreter from a different directory and try again?

Cheers!
Richard

**Comment by TerraVenil** [comment]
Yes, you are absolutely correct. Now it works, it was my mistake that I follow docs from develop branch https://github.com/rrmeister/pyQuEST/tree/develop where this important line was missing.
Thanks.
