### ISSUE TITLE
'pyquest.core.Register' object has no attribute '_coefficient'

### ISSUE THREAD

**Issue by TerraVenil** [rrmeister/pyQuEST#4]
Hi, @rrmeister.
During code exploration found small issue
![image](https://github.com/rrmeister/pyQuEST/assets/6068068/f56e5a7c-fa91-478d-b2c7-2d57e2f4e371)

https://github.com/rrmeister/pyQuEST/blob/7869b5d50c8a75f2323100d15f0d81bc71f2b6be/pyquest/core.pyx#L678-L682

**Comment by rrmeister** [comment]
Ah well spotted, thank you. This is fixed with bd87d73 in develop now.
